// Build the catalog: scan effects/, validate, and emit:
//   - catalog.json           (canonical, full machine-readable index)
//   - assets/catalog.js       (window.__CATALOG__ = {...} for file://-safe gallery)
//   - api/index.json          (lightweight effect summaries, no source — for discovery)
//   - api/themes.json         (theme list + facets)
//   - api/effects/<id>.json    (one full record per effect — fetch just what you need)
//
// Usage: node scripts/build.mjs

import { writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";
import { scanCatalog, ROOT } from "./lib/catalog.mjs";

// Deploy build stamp: the build number is the commit count on the current
// branch, so it increases by itself on every merge to main (i.e. every deploy).
// Written to a gitignored assets/build.js so it never enters the committed,
// staleness-checked artifacts — keeping `npm run build` deterministic in CI.
function buildStamp(version) {
  const git = (cmd, fallback) => {
    try {
      return execSync(cmd, { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] })
        .toString()
        .trim();
    } catch {
      return fallback;
    }
  };
  const build = Number(git("git rev-list --count HEAD", "0")) || 0;
  const sha = git("git rev-parse --short HEAD", "dev");
  const [major = "0", minor = "0"] = String(version).split(".");
  return {
    // single version that bumps forward on every deploy, e.g. 0.5.11
    version: `${major}.${minor}.${build}`,
    release: version, // the hand-set semantic release, e.g. 0.5.0
    build,
    sha,
    builtAt: new Date().toISOString().slice(0, 10),
    repo: "JeanCamposLabs/style-catalog",
  };
}

const { catalog, errors } = scanCatalog();

if (errors.length) {
  console.error(`\n✗ ${errors.length} validation error(s):\n`);
  for (const e of errors) console.error("  - " + e);
  console.error("\nBuild aborted. Fix the errors above and re-run.\n");
  process.exit(1);
}

const jsonPath = join(ROOT, "catalog.json");
const jsPath = join(ROOT, "assets", "catalog.js");

writeFileSync(jsonPath, JSON.stringify(catalog, null, 2) + "\n", "utf8");

const banner =
  "// GENERATED by scripts/build.mjs — do not edit by hand.\n" +
  "// Assigns the full catalog to a global so the gallery works from file://.\n";
writeFileSync(jsPath, banner + "window.__CATALOG__ = " + JSON.stringify(catalog) + ";\n", "utf8");

// Deploy build stamp (gitignored — see buildStamp() above).
const stamp = buildStamp(catalog.version);
writeFileSync(
  join(ROOT, "assets", "build.js"),
  "// GENERATED at build time — do not edit, do not commit.\n" +
    "window.__BUILD__ = " + JSON.stringify(stamp) + ";\n",
  "utf8",
);

// ---- Split, fetchable API (v3 programmatic access) ----
// Regenerate the api/ tree from scratch so deleted effects don't leave stragglers.
const apiDir = join(ROOT, "api");
const apiEffectsDir = join(apiDir, "effects");
if (existsSync(apiDir)) rmSync(apiDir, { recursive: true, force: true });
mkdirSync(apiEffectsDir, { recursive: true });

const SUMMARY_FIELDS = [
  "id", "title", "summary", "theme", "themeTitle",
  "categories", "tags", "tech", "era", "difficulty", "path",
];
const summarize = (e) => Object.fromEntries(SUMMARY_FIELDS.map((k) => [k, e[k]]));

const index = {
  name: catalog.name,
  version: catalog.version,
  counts: catalog.counts,
  // how to fetch a full record from a summary:
  effectEndpoint: "api/effects/{id}.json",
  effects: catalog.effects.map(summarize),
};
writeFileSync(join(apiDir, "index.json"), JSON.stringify(index, null, 2) + "\n", "utf8");
writeFileSync(
  join(apiDir, "themes.json"),
  JSON.stringify({ themes: catalog.themes, facets: catalog.facets }, null, 2) + "\n",
  "utf8",
);
for (const e of catalog.effects) {
  writeFileSync(join(apiEffectsDir, `${e.id}.json`), JSON.stringify(e, null, 2) + "\n", "utf8");
}

console.log(
  `✓ Built catalog: ${catalog.counts.effects} effects across ${catalog.counts.themes} themes.`,
);
console.log(`  → catalog.json`);
console.log(`  → assets/catalog.js`);
console.log(`  → assets/build.js (v${stamp.version} · ${stamp.sha})`);
console.log(`  → api/index.json, api/themes.json, api/effects/*.json (${catalog.effects.length})`);
console.log(`  (built ${new Date().toISOString()})`);
