// Build the catalog: scan effects/, validate, and emit:
//   - catalog.json          (canonical, machine-readable index)
//   - assets/catalog.js      (window.__CATALOG__ = {...} for file://-safe gallery)
//
// Usage: node scripts/build.mjs

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { scanCatalog, ROOT } from "./lib/catalog.mjs";

const { catalog, errors } = scanCatalog();

if (errors.length) {
  console.error(`\n✗ ${errors.length} validation error(s):\n`);
  for (const e of errors) console.error("  - " + e);
  console.error("\nBuild aborted. Fix the errors above and re-run.\n");
  process.exit(1);
}

const jsonPath = join(ROOT, "catalog.json");
const jsPath = join(ROOT, "assets", "catalog.js");

writeFileSync(jsonPath, JSON.stringify(catalog, null, 2) + "\n", "utf8");

const banner =
  "// GENERATED by scripts/build.mjs — do not edit by hand.\n" +
  "// Assigns the full catalog to a global so the gallery works from file://.\n";
writeFileSync(jsPath, banner + "window.__CATALOG__ = " + JSON.stringify(catalog) + ";\n", "utf8");

console.log(
  `✓ Built catalog: ${catalog.counts.effects} effects across ${catalog.counts.themes} themes.`,
);
console.log(`  → catalog.json`);
console.log(`  → assets/catalog.js`);
